### PR TITLE
chore: prepare for Cerebral@0.35.x and Cerebral@next

### PR DESCRIPTION
**Pull request by edgesoft**
- remove Cerebral-view-react Mixin in demo
- update to cerebral@next for demo
- linting everything
- update to cerebral-view-react@next
- update to cerebral-model-immutable
- changed structure of demo app to comply to new website docs
- changed all React components to new connect syntax
- removed React specific folder.
- update README
- update devtools to @next
#33 This pull will fix this issue

### CODE REVIEW

**Comment by edgesoft** [comment]
@Guria waiting for your LGTM

**Comment by Guria** [comment]
Now we also have models exposed as `'cerebral/models/mutable'` and `'cerebral/models/immutable'`:

``` js
import Model from 'cerebral/models/mutable'
import Model from 'cerebral/models/immutable'
import {mutable as Model} from 'cerebral/models'
```

could you also split into 2 commits:

```
chore: prepare for cerebral@0.35.x
```

```
feat: remove components reference implementations

BREAKING CHANGE:
React components removed. Examine new demo implementation for reference.
```

**Comment by edgesoft** [comment]
@Guria Humm, I don't think it's a breaking change. It's just the demo.

**Comment by edgesoft** [comment]
@Guria  Well you are right. If they used the react wrappers it's a breaking change.

**Comment by edgesoft** [comment]
@Guria is this ok?

**Comment by Guria** [comment]
Lgtm.

**Comment by Guria** [comment]
@edgesoft fixed

**Comment by edgesoft** [comment]
Thanks @Guria !

**Pull request merged**
