### PR TITLE
Pr/misc

### LINKED ISSUE #15: React 15 warnings
React 15 complains about controlled and uncontrolled inputs. We can not have defaultValue and value in the inputs. Since cerebral is controlling the input we should remove defaultValue from the demo so we don't get all the warnings in the console.

### PR DESCRIPTION
**Pull request by edgesoft**
- Fix #15 , #14 and #10 
- Added a test
- Updated to React 15

### CODE REVIEW

**Comment by edgesoft** [comment]
I've created a pull request. Please go thru it when you have the time.

**Comment by Guria** [comment]
First commit is definetly not a feat,  all other seems LGTM

**Comment by edgesoft** [comment]
Ok, took the same commit as cerebral-view-react

**Comment by Guria** [comment]
It's a feat for view-react, but here we just update a demo. Take a note that all feat and fix commit will go to release notes

**Comment by edgesoft** [comment]
Ah, ok! Then rebase again...

**Comment by edgesoft** [comment]
Ok, I've rebased the feat to chore and added some linting for test that I squashed.

**Comment by edgesoft** [comment]
> Is there a way no to pass defaultValue instead of resetting it?

You can pass all the props that you need but this is made in a fashion to pass all props. We will go thru this later and rebuild the whole demo app and make it nicer and maybe add it to cerebraljs.com/formsdemo

**Comment by edgesoft** [comment]
Looks like there where a miss on React 15 in cerebral-view-react. Updated it now.

**Comment by Guria** [comment]
Will check pr later today

**Pull request merged**
