### PR TITLE
chore: refactoring out repetitive code

### LINKED ISSUE #2: Merge isValidForm and isValidatingForm
@christianalfoni  In the helpers folder isValidForm and isValidatingForm only has one diff on line 12. Maybe we could remove one of them and merge?

### PR DESCRIPTION
**Pull request by edgesoft**
fix: #2

### CODE REVIEW

**Comment by edgesoft** [comment]
Created a pull request for repetitive code. Please take a look at it when you have the time.

**Comment by Guria** [comment]
definitely not a `chore:` type. use `refactor:` if this change internal and doesn't affects api and behaviour.

**Comment by Guria** [comment]
you did smth wrong  here now :)
`chore(package): semantic-release setup` shouldn't appear in your pr

**Comment by edgesoft** [comment]
I know. Added a question on discord.

**Comment by Guria** [comment]
I suppose to remove latest commit `git reset --hard HEAD~` then do rebase on latest master `git rebase origin\master` (origin here is this repo remote, use your remote name for this repo)

**Comment by edgesoft** [comment]
Need to start over. Really hate this git..... need to read up on this

**Pull request closed without merging**
